import type { Metadata } from 'next';
import './../../styles/global.scss';

export const metadata: Metadata = {
  title: 'Garden',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'bg-background'}>{children}</body>
    </html>
  );
}
