import type { Metadata } from 'next';
import './../../styles/global.scss';
import { Header } from '@/common/components/Header/Header';

export const metadata: Metadata = {
  title: 'Garden',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="bg-background flex w-full flex-col items-center p-4 px-50">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
